// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: "doc",
      id: "intro",
      label: "Introduction",
    },
    {
      type: "category",
      label: "eStay Admin Panel Setup",
      items: [
        "admin/installation",
        "admin/property-management",
        "admin/booking-management",
        "admin/user-management",
        "admin/payment-settings",
        "admin/notification-management",
        "admin/system-configurations",
        "admin/language",
        "admin/privacy-policy",
        "admin/terms-conditions",
        "admin/other-pages",
        "admin/ad-spaces",
        "admin/staff-management",
        "admin/general-settings",
        "admin/update-system",
      ],
    },
    {
      type: "category",
      label: "eStay Admin Panel Installation",
      items: [
        "installation/backup-project",
        "installation/backup-database",
        "installation/install-estay-laravel",
      ],
    },
    {
      type: "category",
      label: "eStay App",
      items: [
        "app/setup",
        "app/app-name",
        "app/app-logo",
        "app/app-color",
        "app/package-name",
        "app/asset-image",
        "app/font",
        "app/server-url",
        "app/settings",
        "app/create-fcm",
        "app/email-fcm",
        "app/google-fcm",
        "app/fb-fcm",
        "app/phone-fcm",
        "app/apple-fcm",
        "app/fcm",
        "app/admob",
        "app/unity-ad",
        "app/ads-interval",
        "app/api",
        "app/change-lang",
        "app/apk",
        "app/app-bundle",
        "app/apk-ios",
        "app/playstore-datasafety",
        "app/debug",
      ],
    },
    {
      type: "category",
      label: "eStay Web",
      items: [
        "web/setup",
        "web/domain-url",
        "web/integrate-firebase",
        "web/mobile-login",
        "web/app-name",
        "web/favicon",
        "web/set-logo-theme-color",
        "web/set-social-media",
        "web/change-meta-info",
        "web/set-sitemap",
        "web/change-fonts",
        "web/add-google-adsense",
        "web/toggle-maintenance-mode",
        "web/run-the-project",
        "web/local-build",
        "web/seo-deploy",
        "web/nextjsdeploy",
      ],
    },
    "support",
    "faqs",
    "feedback",
    "contact",
  ],
};

module.exports = sidebars;
