// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: "doc",
      id: "intro",
      label: "Introduction",
    },
    {
      type: "category",
      label: "eStay Admin Panel Setup",
      items: [
        "admin/installation",
        "admin/property-management",
        "admin/booking-management",
        "admin/user-management",
        "admin/payment-settings",
        "admin/notification-management",
        "admin/system-configurations",
        "admin/language",
        "admin/privacy-policy",
        "admin/terms-conditions",
        "admin/other-pages",
        "admin/ad-spaces",
        "admin/staff-management",
        "admin/general-settings",
        "admin/update-system",
      ],
    },
    {
      type: "category",
      label: "eStay App",
      items: [
        "app/prerequisites",
        "app/firebase-setup",
        "app/firebase-billing",
        "app/panel-url-deeplink",
        "app/change-package-name",
        "app/change-app-name",
        "app/change-app-logo",
        "app/change-theme-color",
        "app/change-app-font",
        "app/notification-settings",
        "app/map-api-key",
        "app/auth-methods",
        "app/payment-gateway",
        "app/manage-languages",
        "app/contact-us",
        "app/maintenance-mode",
        "app/change-app-version",
        "app/store-urls-force-update",
        "app/run-the-app",
        "app/deployment",
      ],
    },
    {
      type: "category",
      label: "eStay Web",
      items: [
        "web/setup",
        "web/domain-url",
        "web/integrate-firebase",
        "web/mobile-login",
        "web/app-name",
        "web/set-logo-theme-color",
        "web/change-meta-info",
        "web/map-api-key",
        "web/set-sitemap",
        "web/change-fonts",
        "web/pwa-setup",
        "web/run-the-project",
        "web/local-build",
        "web/nextjsdeploy",
      ],
    },
    "support",
    "faqs",
    "feedback",
    "contact",
  ],
};

module.exports = sidebars;
